Algoritmo "semnome"
// Disciplina: Fundamentos de Programação
// Professor: Jorge Rabello
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/03/2017
Var
   // Seção de Declarações das variáveis
   i: inteiro
   x : inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Hello guy, put one number here:")
   para i de 0 ate 10.

Fimalgoritmo