Algoritmo "semnome"
// Disciplina: Fundamentos de Programação 
// Professor: Jorge Rabello 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/03/2017
Var
// Seção de Declarações das variáveis 
i , y: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc..

para i de 1 ate 5 faca
para y de 1 ate i faca
escreva("*")
fimpara
escreval()
fimpara



Fimalgoritmo