Algoritmo "semnome"
// Disciplina: Fundamentos de Programação
// Professor: Jorge Rabello
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/03/2017
Var
   // Seção de Declarações das variáveis
I: INTEIRO

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
i<-0

repita
escreval(i)
i<-i+ 1
ate i>10

Fimalgoritmo